Aluno: Igor Barreto

Código de Aluno: 1477042

e-mail: 1477042@sga.pucminas.br

#**Lista de Exercícios: Tensores em PyTorch**

Esta série de exercícios foi projetada para ajudar a consolidar o seu entendimento sobre o uso e manipulação de tensores, que são a base fundamental para o processamento de dados em PyTorch. Os tensores são estruturas de dados multidimensionais que formam a espinha dorsal de operações em aprendizado de máquina e processamento de dados.

Nesta lista, você irá explorar desde conceitos básicos, como a criação e manipulação de tensores, até operações mais avançadas, como broadcasting e reshaping. Ao final, você terá adquirido um sólido entendimento sobre como trabalhar com tensores no ecossistema PyTorch.

Instruções:
- Leia cada exercício atentamente e siga as instruções fornecidas.
- Complete cada exercício no espaço designado.
- Alguns exercícios podem exigir o uso de funções específicas do PyTorch.
- Certifique-se de consultar a documentação oficial quando necessário.

Lembre-se de que a prática é essencial para aprimorar suas habilidades em PyTorch. Vamos começar!

In [ ]:
import torch

## **Exercício 1: Criando Tensores**
Crie um tensor 1D de números inteiros de 1 a 5.

In [ ]:
tensor_1D= torch.IntTensor([1,2,3,4,5])
print(f'Tensor 1D: \n\n{tensor_1D} \n\nTensor type: {tensor_1D.dtype} \nTensor shape: {tensor_1D.shape}\nTensor nDimensions: {tensor_1D.dim()}\nTensor nElements: {tensor_1D.numel()}')

Tensor 1D: 

tensor([1, 2, 3, 4, 5], dtype=torch.int32) 

Tensor type: torch.int32 
Tensor shape: torch.Size([5])
Tensor nDimensions: 1
Tensor nElements: 5


Crie um tensor 2D de números reais de 0 a 8 em uma matriz 2x4.

In [ ]:
tensor_2D= torch.IntTensor([[0, 1, 2, 3],[4, 5, 6, 7]])
print(f'Tensor 2D: \n\n{tensor_2D} \n\nTensor type: {tensor_2D.dtype} \nTensor shape: {tensor_2D.shape} \nTensor nDimensions: {tensor_2D.dim()}\nTensor nElements: {tensor_2D.numel()}')

Tensor 2D: 

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], dtype=torch.int32) 

Tensor type: torch.int32 
Tensor shape: torch.Size([2, 4]) 
Tensor nDimensions: 2
Tensor nElements: 8


##**Exercício 2: Operações Básicas**

Multiplique o tensor 1D do exercicio anterior por 3

In [ ]:
escalar = 3
tensor_1D = tensor_1D= torch.IntTensor([1,2,3,4,5])
result_tensor = 3* tensor_1D
result_tensor

print(f'Multiplicando o tensor 1D por 3: \n\n{tensor_1D} x {escalar} = {result_tensor}')

Multiplicando o tensor 1D por 3: 

tensor([1, 2, 3, 4, 5], dtype=torch.int32) x 3 = tensor([ 3,  6,  9, 12, 15], dtype=torch.int32)


Calcule o produto escala do tensor do exercício anterior com o tensor 1D criado na célula abaixo

In [ ]:
tensor_1d_new = torch.LongTensor([-1, -10, 0, 2, 3])
print(tensor_1d_new)

tensor([ -1, -10,   0,   2,   3])


In [ ]:
result_prod_escalar = tensor_1D * tensor_1d_new
result_prod_escalar

print(f'Produto escalar de 2 tensores: \n\n{tensor_1D} x {tensor_1d_new} = {result_prod_escalar}')

Produto escalar de 2 tensores: 

tensor([1, 2, 3, 4, 5], dtype=torch.int32) x tensor([ -1, -10,   0,   2,   3]) = tensor([ -1, -20,   0,   8,  15])


##**Exercício 3: Operações Avançadas**

Crie um tensor 1D de números inteiros de 1 a 16 e utilize o método view para transformar o tensor em uma matriz 4x4.

In [ ]:
import numpy as np
elements = np.arange(1, 17)
tensor_1D = torch.IntTensor(elements)

print(f'Tensor 1D de números inteiros de 1 a 16: \n\n {tensor_1D }\n\nTensor type: {tensor_1D.dtype} \nTensor shape: {tensor_1D.shape}\nTensor nDimensions: {tensor_1D.dim()}\nTensor nElements: {tensor_1D.numel()}')

Tensor 1D de números inteiros de 1 a 16: 

 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       dtype=torch.int32)

Tensor type: torch.int32 
Tensor shape: torch.Size([16])
Tensor nDimensions: 1
Tensor nElements: 16


In [ ]:
print(f'view matriz 4x4: \n\n {tensor_1D.view(4,4)}')

view matriz 4x4: 

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)


Divida o tensor 1D de 1 a 16 em 4 partes iguais.

In [ ]:
print(f'Dividindo o tensor em 4 partes iguais: \n\n  {tensor_1D.chunk(4)}')

Dividindo o tensor em 4 partes iguais: 

  (tensor([1, 2, 3, 4], dtype=torch.int32), tensor([5, 6, 7, 8], dtype=torch.int32), tensor([ 9, 10, 11, 12], dtype=torch.int32), tensor([13, 14, 15, 16], dtype=torch.int32))


In [ ]:
t_chunk = tensor_1D.chunk(4)
print('Dividindo o tensor em 4 partes iguais: \n')
for i, chunk in enumerate(t_chunk):
  print(f'  chunk{i+1}: {chunk}')

Dividindo o tensor em 4 partes iguais: 

  chunk1: tensor([1, 2, 3, 4], dtype=torch.int32)
  chunk2: tensor([5, 6, 7, 8], dtype=torch.int32)
  chunk3: tensor([ 9, 10, 11, 12], dtype=torch.int32)
  chunk4: tensor([13, 14, 15, 16], dtype=torch.int32)


Crie um novo tensor 2D empilhando essas partes verticalmente.

In [ ]:
# Converta as partes em um tensor 2D
tensor_2D = torch.stack(t_chunk)

print(f'Tensor 2D empilhado: \n  {tensor_2D}')

Tensor 2D empilhado: 
  tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
